### ISSUE TITLE
'GeneratedFeatureFileCodeBehindTask' failure

### ISSUE THREAD

**Issue by user93485938459** [chrisbillson/NUnitRetry.ReqnrollPlugin#7]
When I uninstall and reinstall this repo's package, I can build again. 

As soon as I build again with new tests with this package, I get this error. 

```Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB4018	The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at NUnitRetry.ReqnrollPlugin.RetryGeneratorPlugin.CustomiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPluginInfos, IObjectContainer parentObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection`1 generatorPluginInfos, IObjectContainer rootObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute()
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
C:\Users\user\.nuget\packages\reqnroll.tools.msbuild.generation\2.1.0\build\Reqnroll.Tools.MsBuild.Generation.targets	93	
```

System.CodeDom is a dependency of Reqnroll.CustomPlugin which I have installed (I have also installed 8.0.0.0 for system.codedom directly, same error), so no clue why this is happening.

To get around this locally running tests with retry working, I need to remove Reqnroll.Tools.MsBuild.Generation.targets file or comment out the <GenerateFeatureFileCodeBehindTask> portion in \.nuget\packages\reqnroll.tools.msbuild.generation\2.1.0\build\Reqnroll.Tools.MsBuild.Generation.targets

Have also tried clearing nuget cache, same issue.

---

List of installed packages

```
    <PackageReference Include="Allure.Reqnroll" Version="2.12.1" />
    <PackageReference Include="Azure.Identity" Version="1.10.3" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="EPPlus" Version="6.2.10" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="ExtentReports" Version="4.1.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.54" />
    <PackageReference Include="IdentityModel" Version="6.2.0" />
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="6.1.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.31.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="NUnitRetry.ReqnrollPlugin" Version="1.0.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="2.1.0" />
    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="2.1.0" />
    <PackageReference Include="RestSharp" Version="110.2.0" />
    <PackageReference Include="Selenium.Support" Version="4.15.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.22.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="129.0.6668.7000" />
    <PackageReference Include="nunit" Version="4.2.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageReference Include="FluentAssertions" Version="6.2.0" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="7.0.2" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
    <PackageReference Include="WebDriverManager" Version="2.17.1" />
```

**Comment by user93485938459** [comment]
Not sure if related to the plugin? But I solved this by renaming project reference

System.CodeDom was referencing version 8.0.0 in project file, while the above GenerateFeatureFileCodeBehindTask was looking for 8.0.0.0. Just changed version number.

**Comment by user93485938459** [comment]
Thought renaming proj file reference 

```<PackageReference Include="System.CodeDom" Version="8.0.0" />```

to

```<PackageReference Include="System.CodeDom" Version="8.0.0.0" />```

would fix it, but no luck
