### ISSUE TITLE
Build fails with "GenerateFeatureFileCodeBehindTask" task failed unexpectedly 

### ISSUE THREAD

**Issue by sudgarre** [chrisbillson/NUnitRetry.ReqnrollPlugin#8]
Steps to reproduce:

1. Added `reqnroll.json` available in https://github.com/chrisbillson/NUnitRetry.ReqnrollPlugin/blob/master/tests/NUnitRetry.Tests/reqnroll.json
2. Added Nuget package: 		<PackageReference Include="NUnitRetry.ReqnrollPlugin" Version="1.0.0" />
3. Project build fails with error

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateFeatureFileCodeBehindTask" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.CodeDom, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at NUnitRetry.ReqnrollPlugin.RetryGeneratorPlugin.CustomiseDependencies(Object sender, CustomizeDependenciesEventArgs eventArgs)
   at Reqnroll.Generator.GeneratorContainerBuilder.CreateContainer(ReqnrollConfigurationHolder configurationHolder, ProjectSettings projectSettings, IEnumerable`1 generatorPluginInfos, IObjectContainer parentObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.WrappedGeneratorContainerBuilder.BuildGeneratorContainer(ReqnrollConfigurationHolder reqnrollConfigurationHolder, ProjectSettings projectSettings, IReadOnlyCollection`1 generatorPluginInfos, IObjectContainer rootObjectContainer)
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTaskExecutor.Execute()
   at Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	CP.SSR.UIAutomation	C:\Users\XXXXXX\.nuget\packages\reqnroll.tools.msbuild.generation\2.1.0\build\Reqnroll.Tools.MsBuild.Generation.targets	93

**Comment by chrisbillson** [comment]
Thank you for raising this issue. I will take a look.

**Comment by user93485938459** [comment]
Happening to me also even with latest reqnroll 2.1.1

**Comment by user93485938459** [comment]
@sudgarre This is working for me on nuget as a workaround https://www.nuget.org/packages/databinding.Reqnroll.NUnit.Retry/5.8.8#show-readme-container

**Comment by sudgarre** [comment]
Thanks @user93485938459 , I will have a look

**Comment by chrisbillson** [comment]
So after a bit more investigation, it looks like this _could_ potentially be an underlying issue in Reqnroll. I'm just working to determine root cause with one of the maintainers.

**Comment by Nandini1456** [comment]
I use reqnroll 2.1.1 and facing same issue while building the project. Even after adding System.CodeDom package with v8.0.0 , issue still persists.

**Comment by peter-nguyen-contemi** [comment]
I use Reqnroll 2.2.1 and still have the same error. It seems that the error only occurs when building the solution in Visual Studio. The error doesn't occur when building the solution using JetBrains Rider or the `dotnet build` commandline.

**Comment by chrisbillson** [comment]
This should be fixed when this change goes through https://github.com/reqnroll/Reqnroll/pull/411

**Comment by galadril** [comment]
FYI i dont see this exception anymore with the latest versions
